cache:
  paths:
  - node_modules

pages:
  stage: deploy
  image: node:latest
  script:
  # install dependencies & compile the code
  - "npm install"
  - "npm run compile"

  - "mkdir public"
  - "cp -r compiled/* public"
  artifacts:
    paths:
    - public
  only:
    - master
